--PROYECTO F1
--MODULO:POO
--PROFESOR:LUIS_ALONSO_BOGANTES_RODRIGUEZ
--ESTUDIANTE:JOSE_CAMPOS_CHAVES

--***BORRAR LA BASE DE DATOS***
--DROP DATABASE CLINICA_PRIVADA
--SE CREA LA DB
CREATE DATABASE CLINICA_PRIVADA;
GO

--SE USA LA BD
USE CLINICA_PRIVADA;
GO

-- Creación de la tabla PACIENTES
CREATE TABLE PACIENTES (
  ID_PACIENTE INT PRIMARY KEY IDENTITY,
  NOMBRE_PACIENTE VARCHAR(50),
  APELLIDO1_PACIENTE VARCHAR(50),
  APELLIDO2_PACIENTE VARCHAR(50),
  CEDULA_PACIENTE VARCHAR(9) UNIQUE,
  TELEFONO_PACIENTE VARCHAR(8) NULL,
  CORREO_PACIENTE VARCHAR(50) NULL,
  DIRECCION_PACIENTE VARCHAR(100) NULL,
  FECHA_NACIMIENTO_PACIENTE DATE,
  ESTADO_PACIENTE VARCHAR(3) DEFAULT 'ACT',
  BORRADO_PACIENTE BIT DEFAULT 0
);

-- Creación de la tabla FUNCIONARIOS
CREATE TABLE FUNCIONARIOS (
  ID_FUNCIONARIO INT PRIMARY KEY IDENTITY,
  NOMBRE_FUNCIONARIO VARCHAR(50),
  APELLIDO1_FUNCIONARIO VARCHAR(50),
  APELLIDO2_FUNCIONARIO VARCHAR(50),
  CEDULA_FUNCIONARIO VARCHAR(9) UNIQUE,
  TELEFONO_FUNCIONARIO VARCHAR(8) NULL,
  CORREO_FUNCIONARIO VARCHAR(50) NULL,
  DIRECCION_FUNCIONARIO VARCHAR(100) NULL,
  FECHA_NACIMIENTO_FUNCIONARIO DATE,
  PUESTO_TRABAJO VARCHAR(50),
  ESTADO_FUNCIONARIO VARCHAR(3) DEFAULT 'ACT',
  BORRADO_FUNCIONARIO BIT DEFAULT 0
);

-- Creación de la tabla ESPECIALISTAS
CREATE TABLE ESPECIALISTAS (
  ID_ESPECIALISTA INT PRIMARY KEY IDENTITY,
  NOMBRE_ESPECIALISTA VARCHAR(50),
  APELLIDO1_ESPECIALISTA VARCHAR(50),
  APELLIDO2_ESPECIALISTA VARCHAR(50),
  ESPECIALIDAD VARCHAR(50),
  ESTADO_ESPECIALISTA VARCHAR(3) DEFAULT 'ACT',
  BORRADO_ESPECIALISTA BIT DEFAULT 0,
  ID_FUNCIONARIO INT
);

-- Creación de la tabla USUARIOS_SISTEMA
CREATE TABLE USUARIOS_SISTEMA (
  ID_USUARIO_SISTEMA INT PRIMARY KEY IDENTITY,
  NOMBRE_USUARIO_SISTEMA VARCHAR(50) UNIQUE,
  CONTRASENA_USUARIO_SISTEMA VARCHAR(255),
  ID_FUNCIONARIO INT,
  ESTADO_USUARIO_SISTEMA VARCHAR(3) DEFAULT 'ACT',
  BORRADO_USUARIO_SISTEMA BIT DEFAULT 0
);

-- Creación de la tabla MEDICAMENTOS
CREATE TABLE MEDICAMENTOS (
  COD_MEDICAMENTO INT PRIMARY KEY IDENTITY,
  NOMBRE_MEDICAMENTO VARCHAR(50),
  FABRICANTE_MEDICAMENTO VARCHAR(50),
  FECHA_COMPRA_MEDICAMENTO DATE,
  FECHA_VENCIMIENTO_MEDICAMENTO DATE,
  DESCRIPCION_MEDICAMENTO VARCHAR(100) NULL,
  UNIDADES_MEDICAMENTO INT NULL DEFAULT 1,
  PRECIO_MEDICAMENTO INT,
  ESTADO_MEDICAMENTO VARCHAR(3) DEFAULT 'ACT',
  BORRADO_MEDICAMENTO BIT DEFAULT 0
);

-- Creación de la tabla DIAGNOSTICOS
CREATE TABLE DIAGNOSTICOS (
  COD_DIAGNOSTICO INT PRIMARY KEY IDENTITY,
  DIAGNOSTICO VARCHAR(100),
  DESCRIPCION_DIAGNOSTICO VARCHAR(1000) NULL,
  FECHA_DIAGNOSTICO DATE,
  HORA_DIAGNOSTICO TIME,
  INDICACIONES_DIAGNOSTICO VARCHAR(300) NULL,
  ESTADO_DIAGNOSTICO VARCHAR(3) DEFAULT 'ACT',
  BORRADO_DIAGNOSTICO BIT DEFAULT 0,
  ID_ESPECIALISTA INT,
  COD_MEDICAMENTO INT,
  COD_HISTORIAL_CLINICO INT
);

-- Creación de la tabla HISTORIAL_CLINICO
CREATE TABLE HISTORIAL_CLINICO (
  COD_HISTORIAL_CLINICO INT PRIMARY KEY IDENTITY,
  ID_PACIENTE INT,
  COD_DIAGNOSTICO INT,
  FECHA_HISTORIAL DATE,
  HORA_HISTORIAL TIME,
  OBSERVACIONES VARCHAR(1000) NULL,
  ESTADO_HISTORIAL_CLINICO VARCHAR(3) DEFAULT 'ACT',
  BORRADO_HISTORIAL_CLINICO BIT DEFAULT 0
);

-- Creación de la tabla CITAS
CREATE TABLE CITAS (
  COD_CITA INT PRIMARY KEY IDENTITY,
  ID_USUARIO_SISTEMA INT,
  ID_PACIENTE INT,
  ID_ESPECIALISTA INT,
  MOTIVO_CITA VARCHAR(255),
  FECHA_CITA DATE,
  HORA_CITA TIME,
  DURACION_CITA TIME,
  OBSERVACIONES_CITA VARCHAR(255) NULL,
  ESTADO_CITA VARCHAR(3) DEFAULT 'ACT',
  BORRADO_CITA BIT DEFAULT 0
);

-- Creación de la tabla BITACORA
CREATE TABLE BITACORA (
  COD_BITACORA INT PRIMARY KEY IDENTITY,
  ID_USUARIO_SISTEMA INT,
  HORA_BITACORA TIME,
  FECHA_BITACORA DATE,
  ORIGEN VARCHAR(20),
  ACCION_REALIZADA VARCHAR(50),
  ESTADO_BITACORA VARCHAR(3) DEFAULT 'ACT',
  BORRADO_BITACORA BIT DEFAULT 0
);

-- Creación de la tabla AGENDA
CREATE TABLE AGENDA (
  COD_AGENDA INT PRIMARY KEY IDENTITY,
  ID_ESPECIALISTA INT,
  FECHA_AGENDA DATE,
  HORA_INICIO_AGENDA TIME,
  HORA_FIN_AGENDA TIME,
  ESTADO_AGENDA VARCHAR(3) DEFAULT 'ACT',
  BORRADO_AGENDA BIT DEFAULT 0
);

-- Creación de la tabla FACTURAS
CREATE TABLE FACTURAS (
  COD_FACTURA INT PRIMARY KEY IDENTITY,
  ID_PACIENTE INT,
  FECHA_FACTURA DATE,
  HORA_FACTURA TIME,
  FORMA_DE_PAGO VARCHAR(20) DEFAULT 'EFECTIVO',
  ESTADO_FACTURA VARCHAR(3) DEFAULT 'ACT',
  BORRADO_FACTURA BIT DEFAULT 0
);

-- Creación de la tabla DETALLE_FACTURA
CREATE TABLE DETALLE_FACTURA (
  COD_DETALLE_FACTURA INT PRIMARY KEY IDENTITY,
  COD_FACTURA INT,
  DESCRIPCION_SERVICIO VARCHAR(100),
  MONTO_SERVICIO DECIMAL(10, 2),
  ESTADO_DETALLE_FACTURA VARCHAR(3) DEFAULT 'ACT',
  BORRADO_DETALLE_FACTURA BIT DEFAULT 0
);

-- Agregar restricciones de clave externa después de crear todas las tablas

-- Agregar clave externa a ESPECIALISTAS
ALTER TABLE ESPECIALISTAS
ADD CONSTRAINT FK_ESPECIALISTAS_FUNCIONARIOS
FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO);

-- Agregar clave externa a USUARIOS_SISTEMA
ALTER TABLE USUARIOS_SISTEMA
ADD CONSTRAINT FK_USUARIOS_SISTEMA_FUNCIONARIOS
FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO);

-- Agregar clave externa a DIAGNOSTICOS
ALTER TABLE DIAGNOSTICOS
ADD CONSTRAINT FK_DIAGNOSTICOS_ESPECIALISTAS
FOREIGN KEY (ID_ESPECIALISTA) REFERENCES ESPECIALISTAS(ID_ESPECIALISTA);

ALTER TABLE DIAGNOSTICOS
ADD CONSTRAINT FK_DIAGNOSTICOS_MEDICAMENTOS
FOREIGN KEY (COD_MEDICAMENTO) REFERENCES MEDICAMENTOS(COD_MEDICAMENTO);

ALTER TABLE DIAGNOSTICOS
ADD CONSTRAINT FK_DIAGNOSTICOS_HISTORIAL_CLINICO
FOREIGN KEY (COD_HISTORIAL_CLINICO) REFERENCES HISTORIAL_CLINICO(COD_HISTORIAL_CLINICO);

-- Agregar clave externa a HISTORIAL_CLINICO
ALTER TABLE HISTORIAL_CLINICO
ADD CONSTRAINT FK_HISTORIAL_CLINICO_PACIENTES
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE);

ALTER TABLE HISTORIAL_CLINICO
ADD CONSTRAINT FK_HISTORIAL_CLINICO_DIAGNOSTICOS
FOREIGN KEY (COD_DIAGNOSTICO) REFERENCES DIAGNOSTICOS(COD_DIAGNOSTICO);

-- Agregar clave externa a CITAS
ALTER TABLE CITAS
ADD CONSTRAINT FK_CITAS_USUARIOS_SISTEMA
FOREIGN KEY (ID_USUARIO_SISTEMA) REFERENCES USUARIOS_SISTEMA(ID_USUARIO_SISTEMA);

ALTER TABLE CITAS
ADD CONSTRAINT FK_CITAS_PACIENTES
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE);

ALTER TABLE CITAS
ADD CONSTRAINT FK_CITAS_ESPECIALISTAS
FOREIGN KEY (ID_ESPECIALISTA) REFERENCES ESPECIALISTAS(ID_ESPECIALISTA);

-- Agregar clave externa a FACTURAS
ALTER TABLE FACTURAS
ADD CONSTRAINT FK_FACTURAS_PACIENTES
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE);

-- Agregar clave externa a DETALLE_FACTURA
ALTER TABLE DETALLE_FACTURA
ADD CONSTRAINT FK_DETALLE_FACTURA_FACTURAS
FOREIGN KEY (COD_FACTURA) REFERENCES FACTURAS(COD_FACTURA);



