--PROYECTO F2
--MODULO:POO
--PROFESOR:LUIS_ALONSO_BOGANTES_RODRIGUEZ
--ESTUDIANTE:JOSE_CAMPOS_CHAVES

--***BORRAR LA BASE DE DATOS***
--DROP DATABASE CLINICA_PRIVADA

--SE CREA LA DB
CREATE DATABASE CLINICA_PRIVADA;
GO

--SE USA LA BD
USE CLINICA_PRIVADA;
GO

-- Creación de la tabla PACIENTES
CREATE TABLE PACIENTES (
  ID_PACIENTE INT PRIMARY KEY IDENTITY,
  NOMBRE_PACIENTE VARCHAR(50),
  APELLIDOS_PACIENTE VARCHAR(50),  
  CEDULA_PACIENTE VARCHAR(9) UNIQUE,
  TELEFONO_PACIENTE VARCHAR(8) NULL,
  CORREO_PACIENTE VARCHAR(50) NULL,
  DIRECCION_PACIENTE VARCHAR(100) NULL,
  FECHA_NACIMIENTO_PACIENTE DATE,  
);

-- Creación de la tabla FUNCIONARIOS
CREATE TABLE FUNCIONARIOS (
  ID_FUNCIONARIO INT PRIMARY KEY IDENTITY,
  NOMBRE_FUNCIONARIO VARCHAR(50),
  APELLIDOS_FUNCIONARIO VARCHAR(50),  
  CEDULA_FUNCIONARIO VARCHAR(9) UNIQUE,
  TELEFONO_FUNCIONARIO VARCHAR(8) NULL,
  CORREO_FUNCIONARIO VARCHAR(50) NULL,
  DIRECCION_FUNCIONARIO VARCHAR(100) NULL,
  FECHA_NACIMIENTO_FUNCIONARIO DATE,    
);

-- Creación de la tabla PUESTOS_DE_TRABAJO
CREATE TABLE PUESTOS_DE_TRABAJO (
  ID_PUESTO INT PRIMARY KEY,
  NOMBRE_PUESTO VARCHAR(50),
  DESCRIPCION_PUESTO VARCHAR(100),
  SALARIO DECIMAL(10, 2),
  ID_FUNCIONARIO INT, -- Agregado: ID_FUNCIONARIO como clave externa
  -- Otros atributos relacionados con los puestos de trabajo
  FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS (ID_FUNCIONARIO)
);


-- Creación de la tabla ESPECIALISTAS
CREATE TABLE ESPECIALIDAD (
  ID_ESPECIALIDAD INT PRIMARY KEY IDENTITY,  
  NOMBRE_ESPECIALIDAD VARCHAR(100),
  DESCRIPCION_ESPECIALIDAD VARCHAR(100),
  ID_FUNCIONARIO INT
);

-- Creación de la tabla USUARIOS_SISTEMA
CREATE TABLE USUARIOS_SISTEMA (
  ID_USUARIO_SISTEMA INT PRIMARY KEY IDENTITY,
  NOMBRE_USUARIO_SISTEMA VARCHAR(50) UNIQUE,
  CONTRASENA_USUARIO_SISTEMA VARCHAR(255),
  ID_FUNCIONARIO INT,  
);

-- Creación de la tabla MEDICAMENTOS
CREATE TABLE MEDICAMENTOS (
  ID_MEDICAMENTO INT PRIMARY KEY IDENTITY,
  NOMBRE_MEDICAMENTO VARCHAR(50),
  FABRICANTE_MEDICAMENTO VARCHAR(50),
  FECHA_COMPRA_MEDICAMENTO DATE,
  FECHA_VENCIMIENTO_MEDICAMENTO DATE,
  DESCRIPCION_MEDICAMENTO VARCHAR(100) NULL,
  UNIDADES_MEDICAMENTO INT NULL DEFAULT 1,
  PRECIO_MEDICAMENTO DECIMAL(10, 2)  
);

-- Creación de la tabla DIAGNOSTICOS
CREATE TABLE DIAGNOSTICOS (
  ID_DIAGNOSTICO INT PRIMARY KEY IDENTITY,
  DIAGNOSTICO VARCHAR(100),
  DESCRIPCION_DIAGNOSTICO VARCHAR(1000) NULL,
  INDICACIONES_DIAGNOSTICO VARCHAR(300) NULL, 
  FECHA_DIAGNOSTICO DATE,
  HORA_DIAGNOSTICO TIME,   
  ID_ESPECIALISTA INT,
  ID_HISTORIAL_CLINICO INT
);

-- Creación de la tabla HISTORIAL_CLINICO
CREATE TABLE HISTORIAL_CLINICO (
  ID_HISTORIAL_CLINICO INT PRIMARY KEY IDENTITY,
  ID_PACIENTE INT,
  FECHA_HISTORIAL DATE,
  HORA_HISTORIAL TIME,
  OBSERVACIONES VARCHAR(1000) NULL,  
);

-- Creación de la tabla CITAS
CREATE TABLE CITAS (
  ID_CITA INT PRIMARY KEY IDENTITY,
  ID_USUARIO_SISTEMA INT,
  ID_PACIENTE INT,
  ID_ESPECIALISTA INT,
  MOTIVO_CITA VARCHAR(255),
  FECHA_CITA DATE,
  HORA_CITA TIME,
  DURACION_CITA TIME,
  OBSERVACIONES_CITA VARCHAR(255) NULL,
  ESTADO_CITA VARCHAR(3) DEFAULT 'ACT'  
);

-- Creación de la tabla BITACORA
CREATE TABLE BITACORA (
  ID_BITACORA INT PRIMARY KEY IDENTITY,
  ID_USUARIO_SISTEMA INT,
  HORA_BITACORA TIME,
  FECHA_BITACORA DATE,
  ORIGEN VARCHAR(20),
  ACCION_REALIZADA VARCHAR(50),  
);

-- Creación de la tabla AGENDA
CREATE TABLE AGENDA (
  ID_AGENDA INT PRIMARY KEY IDENTITY,
  ID_ESPECIALISTA INT,
  FECHA_AGENDA DATE,
  HORA_INICIO_AGENDA TIME,
  HORA_FIN_AGENDA TIME,
  ESTADO_AGENDA VARCHAR(3) DEFAULT 'ACT',
  BORRADO_AGENDA BIT DEFAULT 0
);

-- Creación de la tabla FACTURAS
CREATE TABLE FACTURAS (
  ID_FACTURA INT PRIMARY KEY IDENTITY,
  ID_PACIENTE INT,
  FECHA_FACTURA DATE,
  HORA_FACTURA TIME,
  FORMA_DE_PAGO VARCHAR(20) DEFAULT 'EFECTIVO',
  SUBTOTAL DECIMAL(10, 2),
  IMPUESTO DECIMAL(10, 2),
  DESCUENTO DECIMAL(10, 2),
  MONTO_TOTAL DECIMAL(10, 2),
  ESTADO_FACTURA VARCHAR(3) DEFAULT 'ACT'  
);

-- Creación de la tabla DETALLE_FACTURA
CREATE TABLE DETALLE_FACTURA (
  ID_DETALLE_FACTURA INT PRIMARY KEY IDENTITY,
  ID_FACTURA INT,
  DESCRIPCION_SERVICIO VARCHAR(100),
  MONTO_SERVICIO DECIMAL(10, 2)  
);

-- Agregar restricciones de clave externa después de crear todas las tablas

-- Agregar clave externa a ESPECIALISTAS
ALTER TABLE ESPECIALISTAS
ADD CONSTRAINT FK_ESPECIALISTAS_FUNCIONARIOS
FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO);

-- Agregar clave externa a USUARIOS_SISTEMA
ALTER TABLE USUARIOS_SISTEMA
ADD CONSTRAINT FK_USUARIOS_SISTEMA_FUNCIONARIOS
FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO);

-- Agregar clave externa a DIAGNOSTICOS
ALTER TABLE DIAGNOSTICOS
ADD CONSTRAINT FK_DIAGNOSTICOS_ESPECIALISTAS
FOREIGN KEY (ID_ESPECIALISTA) REFERENCES ESPECIALISTAS(ID_ESPECIALISTA);

ALTER TABLE DIAGNOSTICOS
ADD CONSTRAINT FK_DIAGNOSTICOS_HISTORIAL_CLINICO
FOREIGN KEY (ID_HISTORIAL_CLINICO) REFERENCES HISTORIAL_CLINICO(ID_HISTORIAL_CLINICO);

-- Agregar clave externa a HISTORIAL_CLINICO
ALTER TABLE HISTORIAL_CLINICO
ADD CONSTRAINT FK_HISTORIAL_CLINICO_PACIENTES
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE);

-- Agregar clave externa a CITAS
ALTER TABLE CITAS
ADD CONSTRAINT FK_CITAS_USUARIOS_SISTEMA
FOREIGN KEY (ID_USUARIO_SISTEMA) REFERENCES USUARIOS_SISTEMA(ID_USUARIO_SISTEMA);

ALTER TABLE CITAS
ADD CONSTRAINT FK_CITAS_PACIENTES
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE);

ALTER TABLE CITAS
ADD CONSTRAINT FK_CITAS_ESPECIALISTAS
FOREIGN KEY (ID_ESPECIALISTA) REFERENCES ESPECIALISTAS(ID_ESPECIALISTA);

-- Agregar clave externa a FACTURAS
ALTER TABLE FACTURAS
ADD CONSTRAINT FK_FACTURAS_PACIENTES
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE);

-- Agregar clave externa a DETALLE_FACTURA
ALTER TABLE DETALLE_FACTURA
ADD CONSTRAINT FK_DETALLE_FACTURA_FACTURAS
FOREIGN KEY (ID_FACTURA) REFERENCES FACTURAS(ID_FACTURA);

