--PROYECTO F2
--MODULO:POO
--PROFESOR:LUIS_ALONSO_BOGANTES_RODRIGUEZ
--ESTUDIANTE:JOSE_CAMPOS_CHAVES

--***BORRAR LA BASE DE DATOS***
--DROP DATABASE CLINICA_PRIVADA

--SE CREA LA DB

CREATE DATABASE CLINICA_PRIVADA;
GO

--SE USA LA BD
USE CLINICA_PRIVADA;
GO

-- Creación de la tabla PACIENTES
CREATE TABLE PACIENTES (
  ID_PACIENTE INT PRIMARY KEY IDENTITY(1,1),
  NOMBRE_PACIENTE VARCHAR(50),
  APELLIDOS_PACIENTE VARCHAR(50),
  CEDULA_PACIENTE VARCHAR(9),
  TELEFONO_PACIENTE VARCHAR(8) NULL,
  CORREO_PACIENTE VARCHAR(50) NULL,
  DIRECCION_PACIENTE VARCHAR(100) NULL,
  FECHA_NACIMIENTO_PACIENTE DATE
);

-- Creación de la tabla PUESTOS_DE_TRABAJO
CREATE TABLE PUESTOS_DE_TRABAJO (
  ID_PUESTO INT PRIMARY KEY IDENTITY(1,1),
  NOMBRE_PUESTO VARCHAR(50),
  DESCRIPCION_PUESTO VARCHAR(100)
);

-- Creación de la tabla ESPECIALIDADES
CREATE TABLE ESPECIALIDADES (
  ID_ESPECIALIDAD INT PRIMARY KEY IDENTITY(1,1),
  NOMBRE_ESPECIALIDAD VARCHAR(100),
  DESCRIPCION_ESPECIALIDAD VARCHAR(100)
);

-- Creación de la tabla FUNCIONARIOS
CREATE TABLE FUNCIONARIOS (
  ID_FUNCIONARIO INT PRIMARY KEY IDENTITY(1,1),
  ID_PUESTO INT,
  ID_ESPECIALIDAD INT,
  NOMBRE_FUNCIONARIO VARCHAR(50),
  APELLIDOS_FUNCIONARIO VARCHAR(50),
  CEDULA_FUNCIONARIO VARCHAR(9),
  TELEFONO_FUNCIONARIO VARCHAR(8) NULL,
  CORREO_FUNCIONARIO VARCHAR(50) NULL,
  DIRECCION_FUNCIONARIO VARCHAR(100) NULL,
  FECHA_NACIMIENTO_FUNCIONARIO DATE  
);

CREATE TABLE AGENDA_TRABAJO (
  ID_AGENDA INT PRIMARY KEY IDENTITY,
  ID_FUNCIONARIO INT,
  FECHA DATE,
  HORA_INICIO TIME,
  HORA_FIN TIME  
);

-- Creación de las foreign keys
ALTER TABLE FUNCIONARIOS ADD CONSTRAINT FK_FUNCIONARIOS_PUESTOS_DE_TRABAJO
  FOREIGN KEY (ID_PUESTO) REFERENCES PUESTOS_DE_TRABAJO(ID_PUESTO);

ALTER TABLE FUNCIONARIOS ADD CONSTRAINT FK_FUNCIONARIOS_ESPECIALIDADES
  FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES ESPECIALIDADES(ID_ESPECIALIDAD);

ALTER TABLE AGENDA_TRABAJO ADD CONSTRAINT FK_AGENDA_TRABAJO_FUNCIONARIOS
  FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO);

-- Inserción de datos en la tabla PACIENTES
INSERT INTO PACIENTES (NOMBRE_PACIENTE, APELLIDOS_PACIENTE, CEDULA_PACIENTE, TELEFONO_PACIENTE, CORREO_PACIENTE, DIRECCION_PACIENTE, FECHA_NACIMIENTO_PACIENTE)
VALUES
  ('Juan', 'Pérez Gómez', '123456789', '12345678', 'juan@example.com', 'San José, Costa Rica', '1990-05-10'),
  ('María', 'López Torres', '987654321', '87654321', 'maria@example.com', 'Heredia, Costa Rica', '1985-12-15'),
  ('Carlos', 'González Soto', '456789123', '65432198', 'carlos@example.com', 'Alajuela, Costa Rica', '1988-09-20'),
  ('Ana', 'Ramírez Rodríguez', '789123456', '32198765', 'ana@example.com', 'Cartago, Costa Rica', '1992-07-05'),
  ('Luis', 'Fernández Chaves', '654321987', '98765432', 'luis@example.com', 'Puntarenas, Costa Rica', '1983-03-12');



-- Inserción de datos en la tabla PUESTOS_DE_TRABAJO
INSERT INTO PUESTOS_DE_TRABAJO (NOMBRE_PUESTO, DESCRIPCION_PUESTO)
VALUES
  ('Médico', 'Encargado de brindar atención médica y diagnóstico a los pacientes'),
  ('Administrativo', 'Responsable de las tareas administrativas y gestión de la clínica'),
  ('Recepcionista', 'Encargado/a de recibir y atender a los pacientes en la recepción');

-- Inserción de datos en la tabla ESPECIALIDADES
INSERT INTO ESPECIALIDADES (NOMBRE_ESPECIALIDAD, DESCRIPCION_ESPECIALIDAD)
VALUES
  ('', ''),
  ('Medicina General', 'Especialidad médica que se encarga del cuidado integral de la salud de los pacientes'),
  ('Pediatría', 'Especialidad médica que se enfoca en la atención y cuidado de los niños y adolescentes'),
  ('Ginecología', 'Especialidad médica que se ocupa de la salud del aparato reproductor femenino');

-- Inserción de datos en la tabla FUNCIONARIOS
--DELETE FUNCIONARIOS
INSERT INTO FUNCIONARIOS (ID_PUESTO, ID_ESPECIALIDAD, NOMBRE_FUNCIONARIO, APELLIDOS_FUNCIONARIO, CEDULA_FUNCIONARIO, TELEFONO_FUNCIONARIO, CORREO_FUNCIONARIO, DIRECCION_FUNCIONARIO, FECHA_NACIMIENTO_FUNCIONARIO)
VALUES
  (2, 1, 'Juana', 'Gonzales', '123456777', '12345777', 'juana@example.com', 'San José', '1990-05-15'),
  (1, 2, 'Juan', 'Pérez', '123456789', '12345678', 'juan@example.com', 'San José', '1990-05-10'),
  (1, 2, 'María', 'López', '987654321', '87654321', 'maria@example.com', 'Heredia', '1985-12-15'),
  (1, 3, 'Carlos', 'González', '456789123', '65432198', 'carlos@example.com', 'Alajuela', '1988-09-20'),
  (1, 1, 'Ana', 'Ramírez', '789123456', '32198765', 'ana@example.com', 'Cartago', '1992-07-05'),
  (1, 2, 'Luis', 'Fernández', '654321987', '98765432', 'luis@example.com', 'Puntarenas', '1983-03-12');

-- Inserción de datos en la tabla AGENDA_TRABAJO
INSERT INTO AGENDA_TRABAJO (ID_FUNCIONARIO, FECHA, HORA_INICIO, HORA_FIN)
VALUES
  (2, '2023-06-20', '08:00:00', '12:00:00'),
  (2, '2023-06-21', '14:00:00', '18:00:00'),
  (2, '2023-06-22', '09:00:00', '13:00:00');

-- Verificación de los datos insertados en la tabla PACIENTES
SELECT * FROM PACIENTES;

-- Verificación de los datos insertados en la tabla FUNCIONARIOS
SELECT * FROM FUNCIONARIOS;

--SELECT * FROM FUNCIONARIOS F
--LEFT JOIN ESPECIALIDADES E ON F.ID_ESPECIALIDAD = E.ID_ESPECIALIDAD

-- Verificación de los datos insertados en la tabla PUESTOS_DE_TRABAJO
SELECT * FROM PUESTOS_DE_TRABAJO;

-- Verificación de los datos insertados en la tabla ESPECIALIDADES
SELECT * FROM ESPECIALIDADES;

-- Verificación de los datos insertados en la tabla AGENDA_TRABAJO
SELECT * FROM AGENDA_TRABAJO;
